language: node_js

os: linux

node_js:
  - node

dist: xenial

addons:
  chrome: stable
  sonarcloud:
    organization: 'martins86'
    token:
      secure: 57a82ee65a2f2a92c020e8b73d717c12a36763ed

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install -g @angular/cli@13.2.5 sonarqube-scanner
  - npm install

before_install:
  - export DISPLAY=:99.0
  - export NODE_OPTIONS=--openssl-legacy-provider
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test:ci
  - npm run sonar
  - npm run build
  - cd dist/portal
  - cp index.html 404.html

branches:
  only:
    - master

env:
  - EMBER_VERSION=release

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN_TRAVIS
  local_dir: dist/portal
  on:
    branch: master
