language: node_js

node_js:
  - 17

sudo: required

os: linux

dist: xenial

services:
  - xvfb

addons:
  chrome: stable
  sonarcloud:
    organization: 'martins86'
    token:
      secure: $SONAR_CLOUD_TOKEN

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install -g @angular/cli@13.2.5 sonarqube-scanner jest
  - npm install

before_install:
  - export DISPLAY=:99.0
  - export NODE_OPTIONS=--openssl-legacy-provider

script:
  - npm run lint
  - npm run test:ci
  - npm run sonar

before_deploy:
  - npm run build:ci
  - cd dist/portal
  - cp index.html 404.html

notifications:
  email:
    recipients:
      - martins86@gmail.com

branches:
  only:
    - master

env:
  - EMBER_VERSION=release

deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN_TRAVIS
  local_dir: dist/portal
  on:
    branch: master
