name: Portal CI/CD

on:
  push:
    branches: [master, add-gh-actions]

jobs:
  portal-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install and Build CI
        if: success()
        run: |
          npm install && npm run build:gh

      - name: Lint
        if: success()
        run: |
          npm run lint

      - name: Test Unit
        if: success()
        run: |
          npm run test:ci

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: mfe-portal
          path: dist

      - name: Download build
        if: success()
        uses: actions/download-artifact@v1
        with:
          name: mfe-portal

      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist/portal
